### ISSUE TITLE
Users total likes

### ISSUE THREAD

**Issue by petermumford** [schneems/likeable#19]
Hi, firstly it's worth noting that I'm new to redis. I would like to get a total of all likes from a single user across all models. From what I can see there isn't a method in the 'Likeable::UserMethods' class which can do this?

I know you've said your not maintaining this gem no more but I was wondering if you could give me some tips or hints on how I can implement the above function. Any help would be greatly appreciate as I'd like to learn redis a lot more.

Thank you.

**Comment by schneems** [comment]
I would use the callbacks and a redis counter.

after a user likes something, increment a user count key "user:likes:total:count" or something. When a user unlikes that item, decrement the counter.

You could iterate through all users if you only ever need to do this once, but I wouldn't recommend it. You would need to hack this functionality into likeable.

**Comment by petermumford** [comment]
Thanks for getting back. So your basically saying to create another key within redis which holds the total number of likes for a user, which in turn means it will create a new key for every user with a total number of likes.

I'll research into callbacks and redis counter - sounds simple enough, just need to know how to do it the redis way of things.

**Comment by bemurphy** [comment]
@schneems @petermumford another alternative to using ActiveModel style callbacks is to write a module to wrap the `like!` and `unlike!` methods in `Likeable::UserMethods`.  I imagine something like this would work:

``` ruby
module LikeClassCounter
  def like!(obj)
    rtn = super
    RedisTotalLikesCounter.incr(self, obj)
    rtn
  end
end
```

And then include that in after you include the Likeable::UserMethod module.  RedisTotalLikesCounter is obviously some other dependency you create for the totals counting.

The downside to this and the callback method to be on the lookout for is it takes no advantage of redis style transactions.  So if your power fails between those two commands, you might have inconsistent data.  It may be possible to wrap it in a multi but redis transactions aren't my strong spot.  See here for more info:

http://redis.io/topics/transactions

Regarding learning more redis, if you haven't checked out the [Redis Cookbook](http://rediscookbook.org/) it's got some simple examples.  Also, I found [Redis in Action](http://www.manning.com/carlson/) to cover redis at a much more advanced level than much of the coverage out there, once you get more comfortable.  The examples are in python but they are easy enough to read even if you don't know the language.  Lastly, Mathias Meyer has a few blog posts you might find helpful (http://www.paperplanes.de/tags/redis.html).

Hope this is helpful,
--Brendon

**Comment by petermumford** [comment]
@bemurphy thank you for the information. The more I look into Redis the more I like it, specially when it comes to things like this gem. I'll take a look at the links you've supplied.

So this is what I've got so far and works. To count up the likes I've got `Likeable.redis.hincrby('user:likes:total:count', user.id, 1)` which is placed within the 'Likeable.rb' files method `add_like_from(user, time = Time.now.to_f)`. It will run this line after the second `hset` is called and then in my view I have `<%= current_user.total_likes %>` and then in my 'user_methods.rb' file I have the below method, which will fetch my users total likes:

```
def total_likes
    Likeable.redis.hget('user:likes:total:count', self.id)
end
```

This all works fine but what I'd like to happen is from the total_likes method call a method within the 'Likeable.rb' file to run this Redis command so it keeps all the redis calls in one file. I've been trying to call a method within the 'Likeable.rb' file but it keeps falling. Would you know why this might be? The method I'm trying to call within the 'Likeable.rb' file and under the 'ClassMethods' module is below:

```
def get_total_user_likes(user)
    Likeable.redis.hget('user:likes:total:count', user.id)
end
```

So then my method within 'user_methods.rb' would become the below:

```
def total_likes
    get_total_user_likes(self)
end
```
