### ISSUE TITLE
Likeable has some where calls

### ISSUE THREAD

**Issue by bemurphy** [schneems/likeable#3]
Likeable has 2 calls to where finders.  It should probably rely on the find_one/find_many procs.

Also, .all_liked_by_ids is mapping using .to_i:

``` ruby
def all_liked_ids_by(user)
  key = user.like_key(self.to_s.downcase)
  ids = (Likeable.redis.hkeys(key)||[]).map(&:to_i)
end
```

when .to_s would probably work and then allow it to support hash ids like Mongoid uses.

I might hack on this if I get time later.

**Comment by schneems** [comment]
closing this out in favor of your pull request, i'll get a good chance to go over it on monday, thanks for the interest.
