### ISSUE TITLE
How can I get most liked items?

### ISSUE THREAD

**Issue by hendragunz** [schneems/likeable#9]
For example, I have model Product with likable, 
how can I get the most liked product (popular product) that ordered from high to low... :)

THank's :-)

**Comment by schneems** [comment]
We use solr to index our like counts. You could also persist the like count total values in a RDBMS or increment a counter in Redis using the after_like callback. Currently @bigfleet is looking to add a leaderboard and might have some other ideas.

**Comment by bigfleet** [comment]
@hendragunz  Indeed, I'll begin work on this concept next week.  I'll invite your participation on my fork-- I'll let you know in this ticket when that work begins.
